In [3]:
import numpy as np

# 1. Create a NumPy array representing a small image (e.g., 3x3)
small_image = np.array([
    [50, 100, 150],
    [75, 125, 175],
    [20, 60, 220]
], dtype=np.uint8)

# 2. Print its shape
print(f"Original 2D Image Shape: {small_image.shape}")
print("Original 2D Image:\n", small_image)

# 3. Modify individual pixels
small_image[0, 0] = 255  # Set top-left pixel to maximum brightness
small_image[2, 1] = 0    # Set bottom-middle pixel to black
print("\nModified Image:\n", small_image)

# 4. Create a grayscale matrix (4x4 2D matrix)
grayscale_matrix = np.zeros((4, 4), dtype=np.uint8)
grayscale_matrix[1:3, 1:3] = 180  # Add a lighter inner square
print(f"\nGrayscale Matrix Shape: {grayscale_matrix.shape}")
print("Grayscale Matrix:\n", grayscale_matrix)

# 5. Create an RGB image array (Height x Width x Channels -> 3x3x3)
rgb_image = np.zeros((3, 3, 3), dtype=np.uint8)
rgb_image[0, 0] = [255, 0, 0]    # Top-left: Red
rgb_image[1, 1] = [0, 255, 0]    # Center: Green
rgb_image[2, 2] = [0, 0, 255]    # Bottom-right: Blue
print(f"\nRGB Image Shape: {rgb_image.shape}")
print("RGB Image (Red channel):\n", rgb_image[:, :, 0])

# 6. Resize the array using NumPy concepts (Nearest Neighbor via np.repeat)
# Scale up a 2x2 section by 2x along height (axis 0) and width (axis 1)
sample_patch = small_image[:2, :2]
resized_image = np.repeat(np.repeat(sample_patch, 2, axis=0), 2, axis=1)
print(f"\nSample Patch Shape: {sample_patch.shape}")
print(f"Resized Image Shape (scaled 2x): {resized_image.shape}")
print("Resized Image:\n", resized_image)

# 7. Normalize values from 0–255 to 0–1
normalized_image = rgb_image.astype(np.float32) / 255.0
print(f"\nNormalized Image Data Type: {normalized_image.dtype}")
print(f"Normalized Value Range: min={normalized_image.min()}, max={normalized_image.max()}")
print("Normalized Top-Left Pixel (RGB):", normalized_image[0, 0])

Original 2D Image Shape: (3, 3)
Original 2D Image:
 [[ 50 100 150]
 [ 75 125 175]
 [ 20  60 220]]

Modified Image:
 [[255 100 150]
 [ 75 125 175]
 [ 20   0 220]]

Grayscale Matrix Shape: (4, 4)
Grayscale Matrix:
 [[  0   0   0   0]
 [  0 180 180   0]
 [  0 180 180   0]
 [  0   0   0   0]]

RGB Image Shape: (3, 3, 3)
RGB Image (Red channel):
 [[255   0   0]
 [  0   0   0]
 [  0   0   0]]

Sample Patch Shape: (2, 2)
Resized Image Shape (scaled 2x): (4, 4)
Resized Image:
 [[255 255 100 100]
 [255 255 100 100]
 [ 75  75 125 125]
 [ 75  75 125 125]]

Normalized Image Data Type: float32
Normalized Value Range: min=0.0, max=1.0
Normalized Top-Left Pixel (RGB): [1. 0. 0.]
